### ISSUE TITLE
Bug - Topology Pipelines - Update status icon and color to match the new design.

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/react-topology#12]
**Describe the problem**

Topology pipelines staus icons, colors should be matching the latest design spec

![image](https://user-images.githubusercontent.com/9964343/193826561-0a17ed8b-01da-416c-95c5-042b0535a4f0.png)

1.  Running/Pending status colors needs to be matched with above design.
2.  zoomed out nodes (low details) should contain icons. 
3.  configuration options to show/hide the icons on the zoom nodes.

/cc @karthikjeeyar

**Comment by jeff-phillips-18** [comment]
from @andrew-ronaldson

Brain dump starting:
1. For the pending tasks I was thinking it could be light blue if it was the next task (or group of tasks) in the run rather than all pending tasks. If you are starting a pipelineRun almost all the nodes would be light blue and not necessarily useful.
2. On the other hand the light blue pending style would separate pending from cancelled or skipped tasks.

Curious what you think about those options @serenamarie125

**Comment by jeff-phillips-18** [comment]
from @andrew-ronaldson

> This would then be the same as selected

That is true for nodes with no associated status. The running icon helps with that but only if it is included. Would the running tasks work better as the light blue and all pending tasks are grey? 
<img width="940" alt="Screen Shot 2022-10-06 at 12 16 32 PM" src="https://user-images.githubusercontent.com/28658548/194351627-ee77d80c-0761-4e9f-aef6-fa8fc5a224f9.png">


Option 2 in my screenshot above should be the running task styling so it stands out from the default selected states.


As per my earlier suggestions about pending tasks I will leave that out for the time being in favour of getting this out in product.

**Comment by andrew-ronaldson** [comment]
Option 2, please. Thanks Jeff.

**Comment by serenamarie125** [comment]
Is that light blue blue-200 from PatternFly @jeff-phillips-18 ?

**Comment by serenamarie125** [comment]
If so, it doesn't pass the contrast checker @jeff-phillips-18 @andrew-ronaldson
