### ISSUE TITLE
NaN errors in console from SVG components

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-topology#184]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

**How do you reproduce the problem?**

See https://github.com/opendatahub-io/odh-dashboard/pull/2725#issuecomment-2084143421

There are NaN errors in the RHOAI console coming from attributes used on SVG components.

**Comment by jeff-phillips-18** [comment]
This was fixed by #173 

Specific change is: https://github.com/patternfly/react-topology/pull/173/files#diff-3fac288e3650a6ea4569063a20a71c99144ee01382762b0e6189e16af1906d0aR237
