### ISSUE TITLE
Pipelines: Update Expanded Group Label Styling to Match Collapsed Styling

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-topology#204]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

Expanded label styling should match collapsed group styling - keep white pill shape and include status. 

<img width="226" alt="Screenshot 2024-05-30 at 4 13 38 PM" src="https://github.com/patternfly/react-topology/assets/32821331/f7d43e55-0923-43f8-98f8-90a27fbacd91">
<img width="152" alt="Screenshot 2024-05-30 at 4 13 44 PM" src="https://github.com/patternfly/react-topology/assets/32821331/12da5310-9909-4e3e-a9c4-90b20d8c525c">

**What is your product and what release date are you targeting?**

RHOAI 2.11

**Comment by jeff-phillips-18** [comment]
Closed by #221
