### ISSUE TITLE
Update Side Panel Behavior to Pan Graph on Node Selection

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-topology#207]
**Describe the problem**

Currently if we select a node and the side panel opens, the node is obscured by the panel. 

When a node is selected, we should translate the graph over to pan the node into view. 

Current:
<img width="700" alt="Screenshot 2024-05-31 at 2 05 00 PM" src="https://github.com/patternfly/react-topology/assets/32821331/351d4c06-37cb-4bc4-a36e-b7c8c0933e65">

Proposed:
<img width="700" alt="Screenshot 2024-05-31 at 2 06 17 PM" src="https://github.com/patternfly/react-topology/assets/32821331/1d72ca86-62e2-466a-b105-a1d62032d3c8">

**What is your product and what release date are you targeting?**
RHOAI 2.11

**Comment by jeff-phillips-18** [comment]
The application needs to handle the selection event and use the Graph's `panIntoView` function. This used to be in the demo app but somehow it got lost. I will add it back as an example for applications to follow.
