### ISSUE TITLE
Add ability to show a group's label on hover

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/react-topology#213]
**Describe the problem**
When zoomed out and not showing details, I would like to see the group's label show up when I hover over the group to give me access to the actions (expand, collapse, context menu).

**How do you reproduce the problem?**
Zoom out to where details are not shown, hover on a group. You see the group get highlighted but you don't see its label.

**Expected behavior**
Highlight the group and show its label

**Is this issue blocking you?**
no

**Screenshots**
![image](https://github.com/patternfly/react-topology/assets/11633780/e2896635-db78-4c07-a4cd-f72c4568831b)

**Comment by jshaughn** [comment]
+1 to this request, would like to see this in PFT 5, thanks!
