### ISSUE TITLE
RFE: Selection-based zoom

### ISSUE THREAD

**Issue by jshaughn** [patternfly/react-topology#222]
Larger graphs are typically zoomed out such that detail is lacking.  It can be useful to quickly zoom in on an "area of interest",  
one where there may be red or orange status, for example.

The ability to select a rectangle region and have that immediately adjust the pan-zoom would be great.  In a different graphing package (cytoscape) we have this implemented with "shift-drag" to select a box.  We are trying to migrate to PFT, and this is currently on our list of blocking feature-gaps.  It looks like this:

![shift-drag](https://github.com/patternfly/react-topology/assets/2104052/f7d0bacf-2a62-4598-a62f-35b272e05e56)

This is the Kiali project, UI for for Istio service mesh, and part of RH OpenShift Service Mesh.  Note that we are currently on PF5.

Thanks!

**Comment by jshaughn** [comment]
@nicolethoen Any chance something like this may be added for 5.4?

**Comment by nicolethoen** [comment]
@jshaughn sorry this slipped past my radar!

we could explore implementing this feature or something similar in an extra PF5 release of topology.

Could you let me know if this is still relevant and how soon you'd like it?
I"m not sure just from this issue how complex the request is - any suggestions or thoughts on that would be welcome as well!

**Comment by jshaughn** [comment]
Hi @nicolethoen , It is still something we'd like to see, it's very useful to zoom into non-trivial topologies based on some easy to identify feature (like red nodes+edges), when you have no labels etc...   But, I have no idea how difficult it is to implement for PFT.  Note that fundamentally this is an ask for being able to select a boxed region and maybe be notified of the captured elements.  It wouldn't necessarily need to be tied to zoom+pan, although I think that's a typical use case, so it would be nice as an example.

**Comment by jshaughn** [comment]
Hi @nicolethoen I forgot to answer the "how soon" question...  as soon as possible, definitely in V5.  We are releasing Kiali with PFT graph very soon and would love to have this for a patch version before too long.

**Comment by jshaughn** [comment]
This is looking great, I think it can be closed. as Done.

**Comment by jeff-phillips-18** [comment]
Closed by #248
