### ISSUE TITLE
Add an option to hide the kebab toggle in the context menu

### ISSUE THREAD

**Issue by ferhoyos** [patternfly/react-topology#237]
Currently, the context menu in the patternfly topology can be opened in two ways: through the kebab toggle on the label or by right-clicking on the node. From a user experience perspective, having two actions that perform the same function might not be ideal.

For this reason, I think it would be good to add support in patternfly topology to choose how the context menu is opened—whether through the kebab toggle, right-clicking, or both. This would give developers the flexibility to decide how the context menu is opened in their applications.

**Comment by dlabaj** [comment]
@jenny-s51 @jeff-phillips-18 Thoughts on the difficulty of adding this functionality?

**Comment by jeff-phillips-18** [comment]
@dlabaj Very simple to add.

@ferhoyos Please know that we are also working on [Unable to use context menu when zoomed out to hide labels](https://github.com/patternfly/react-topology/issues/247), which is a reason you suggested this feature.

**Comment by ferhoyos** [comment]
Thanks @jeff-phillips-18 for the update.
