### ISSUE TITLE
Allow custom icons for DefaultTaskGroup

### ISSUE THREAD

**Issue by jpuzz0** [patternfly/react-topology#240]
A design requirement for Openshift AI is to allow for `BanIcon` to be used instead of the default 'Canceled' task icon.

Default presentation for `DefaultTaskGroup` for the 'Canceled' task node state:  
![Image](https://github.com/user-attachments/assets/a688db1a-ace1-476e-aa3c-9df73433d542)

Desired outcome: The warning icon to be replaced by some user defined icon.

The ability to overwrite the mapping for what icons map to what `RunStatus` at a broader level in a topology view could also be a solution to this problem.

**Comment by dlabaj** [comment]
@jenny-s51 @jpuzz0 Do you know the urgency of this issue?

**Comment by jenny-s51** [comment]
Hi @jpuzz0 , thanks for opening this issue! Topology currently provides support for a `customStatusIcon`, that you can use in [TaskNode.tsx](https://github.com/patternfly/react-topology/blob/02f6fbe50d82c890b210ad6476d0931710be82ea/packages/module/src/pipelines/components/nodes/TaskNode.tsx#L40).
 
You can see an example of this in action in our [demo app](https://custom-status-icon.surge.sh/) (look for Pipelines -> Task Nodes), where the `BanIcon` is passed in to the "Custom Status Icon Task" node: https://github.com/patternfly/react-topology/blob/02f6fbe50d82c890b210ad6476d0931710be82ea/packages/demo-app-ts/src/demos/pipelinesDemo/useDemoPipelineNodes.tsx#L284-L285

Does this help with your use case?

**Comment by jpuzz0** [comment]
@dlabaj 

> [@jenny-s51](https://github.com/jenny-s51) [@jpuzz0](https://github.com/jpuzz0) Do you know the urgency of this issue?

I would consider it normal urgency

**Comment by andrewballantyne** [comment]
> @dlabaj 
> 
> > @jenny-s51 @jpuzz0 Do you know the urgency of this issue?
> 
> I would consider it normal urgency

@jpuzz0 and I talked about this in Standup. I feel this is a bit higher than normal as it is confusing to the user to "what is the feedback you want me to get from the warning". I would not consider this critical, but in there is a status between normal and critical I feel it is probably that. Better to fix this than let it linger imo.

**Comment by jenny-s51** [comment]
Closed via #246
