### ISSUE TITLE
Sync main with latest fixes in the v5 branch

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-topology#251]
Apply all changes from:

- #248 
- #249 
- #250 

cc @nicolethoen @dlabaj

**Comment by jeff-phillips-18** [comment]
@andrew-ronaldson will need to provide the v6 tokens for the selection area for #248

**Comment by jeff-phillips-18** [comment]
For v6, we want the selection area to be:
fill: --pf-t--global--background--color--inverse--default at 20%
stroke: --pf-t--global--color--brand--clicked

We do a 1px dashed line on drag areas if possible. If not solid is fine
