### ISSUE TITLE
Tooltip is only triggered when hovering label text

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/react-topology#257]
This was something brought up in the RHOAI PF v6 migration UI review, but looks like it's also something that was present in v5 as well. Basically a tooltip seems to only get triggered when the text of a node itself is hovered, rather than when the node is hovered. Note in the video below the tooltip for a truncated node triggers only when the cursor hovers the text; there's the area around the text (but within the node outline) where the tooltip is not triggered (recording is from a cluster using PF v5, but this is present in the v6 migration, too):

https://github.com/user-attachments/assets/90918993-1ea0-4658-9d68-ed39145e1ce7

**Comment by jeff-phillips-18** [comment]
@thatblindgeye I believe this is intentional. It has been this way for a long time anyhow. 
@andrew-ronaldson Any thoughts? Badges have their own tooltip so I'm not sure we want the tooltip on the entirety of the node.

**Comment by jeff-phillips-18** [comment]
Closing as works as designed
