### ISSUE TITLE
Audit dark theme in topology

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/react-topology#49]
As part of delivering v5, we need to make sure that the existing dark theme is implemented correctly in topology.

Part of v5 is adding the dark theme switcher to patternfly.org, so any dark theme inconsistencies in topology will be apparent in the documentation.

**Comment by jessiehuff** [comment]
Design issue: https://github.com/patternfly/patternfly-design/issues/1261

**Comment by jessiehuff** [comment]
Completed with following [feedback doc](https://docs.google.com/document/d/1cvhnDIN2e93dwZvXDxrHNtFvSVPz-Hu-YgzI3XMO5kM/edit#heading=h.u72v1vja0ekg)
