### ISSUE TITLE
Spike: investigate current dependencies

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/react-topology#54]
We should probably spend some time cleaning up Topology/dependencies (d3, mobx, etc.) We should likely bump the versions and determine work needed/impact. Versioning checks for all of our CSS (what are the consequences of not pulling in versioned CSS, will this impact our ability to theme Topology in the future?)

**Comment by jenny-s51** [comment]
Following conversation with @jeff-phillips-18 this morning, he suggested that we split this up into separate issues to handle mobx and d3 individually. As part of this spike investigation I bumped mobx and mobx react, however upgrading to these latest major versions breaks the demos and will require topology updates, this will be tracked in #16

**Comment by jessiehuff** [comment]
Created issue for d3 upgrade: https://github.com/patternfly/react-topology/issues/57

Given that I think there's a better understanding of what will be required for these updates, I'm closing this spike.
