### ISSUE TITLE
Resizing the browser does not cause the the svg in the VisualizationSurface to resize

### ISSUE THREAD

**Issue by dagda1** [patternfly/react-topology#62]
**Describe the problem**

Looking at the code in the `VisualizationSurface`, I can see that `ReactMeasure` is used which triggers an `onMeasure` callback when the browser is resized.

```ts
  const onMeasure = React.useMemo(
    () =>
      _.debounce<any>(
        action((contentRect: { client: { width: number; height: number } }) => {
          controller.getGraph().setDimensions(new Dimensions(contentRect.client.width, contentRect.client.height));
        }),
        100,
        { leading: true, trailing: true }
      ),
    [controller]
  );
```

The `onMeasure` function is triggered but the svg does not resize.

**How do you reproduce the problem?**
In this repo run:

1. `yarn install`
2. `yarn workspace demo-app-ts run start:demo-app`
3. go to `http://localhost:3000/topology-pipelines-demo-nav-link` and resize the browser, only the sidebar will change.

**Expected behavior**
The svg should resize to the new contentRect passed to the `onMeasure` callback.

**Is this issue blocking you?**
No

**Screenshots**

https://github.com/patternfly/react-topology/assets/118328/edba556f-2c49-4148-9d24-cc8814ec33dc

**What is your environment?**
- OS: OSX ventura
- Browserchrome
- version 113

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by dagda1** [comment]
> @dagda1 The graph does resize but the elements do not change their scale or location. If you try the `Topology package` demo, you can see that the `fit to screen` control button does fit to the appropriate size when the browser is resized. If you inspect the graph, you can see it's size update as you resize the window.

Thank you for the quick response.  I am looking a the Topology package demo and I had to look at the source to find the button and cancel some styles to make it visible but even with that clicked, the svg does not redraw after a browser resize.

Apologies if i am missing something obvious, I'm new to this package.

Is there a way for the nodes to recalculate or redraw after a resize?


https://github.com/patternfly/react-topology/assets/118328/87c89727-9330-48d4-93eb-408379ef72c0

**Comment by jeff-phillips-18** [comment]
The graph surface does resize, the nodes do not (the scale remains the same). The graph origin remains the same as well. So, the graph does not redraw but shows the portion of the graph that remains in view. After resize, a `fit to screen` would then update the scale and origin such that the entire graph fits on the visible surface. The purpose of the `measure` is only to know the size of the surface in order for the `graph.fit()` function to perform properly.

**Comment by dagda1** [comment]
It does sound like it is possible in theory to do what I want through the API.

What would it look like in code for this to happen as it is not happening automatically.

I have set `controller.setFitToScreenOnLayout(true);` 

Should I use a ResizeObserver or something and call `controller.getGraph().fit()` or something like that to make this happen.

**Comment by dagda1** [comment]
or even

```ts
controller.getGraph().reset();
controller.getGraph().layout();
```

**Comment by jeff-phillips-18** [comment]
Yes, `fit()` would keep the layout intact (node positions would remain the same). If you were to `reset` and `layout`, you would recompute node positions each time it was resized (losing any user drags and such).

**Comment by dagda1** [comment]
I think I am missing why not repositioning the nodes is a good thing.

Would it be possible to know why that is preferable.  It seems bad to me that nodes are no longer visible after a resize

**Comment by dagda1** [comment]
Thank you for taking the time to answer the questions.

**Comment by jshaughn** [comment]
I think that in general users prefer an automatic re-layout on a resize of the graph canvas, without a manual action.  But I respect that the default behavior may not do it.  I think it would be good to add something like an `onResize` callback for the graph, so that we could easily make it happen without having to add our own resize-detector.
