### ISSUE TITLE
How can I assign a different icon for a node that is not associated with RunStatus

### ISSUE THREAD

**Issue by dagda1** [patternfly/react-topology#65]
**Describe the problem**

I am using the Topology pipeline and the `PipelineDagreLayout`.

I need to display a different icon depending on certain conditions other than the status.

![step](https://github.com/patternfly/react-topology/assets/118328/c250a2b7-e80b-43b6-9473-a99689bc266c)

At the moment, the only way I can change the icon is dictated by setting the data property's `status` field to a value from the `RunStatus` enum.

I can see in [the source](https://github.com/patternfly/react-topology/blob/d4d05b9d75b1f4475b7708d25da1037b8f51ce59/packages/module/src/components/nodes/DefaultNode.tsx#L178) where this happens but I have no idea how I can somehow create a custom node that can override this behaviour and somehow get my own icon in there.

I would be grateful for any pointers on how to do this.

**Comment by dagda1** [comment]
@jeff-phillips-18 I've created #66 as a first stab at this.

**Comment by dagda1** [comment]
@dagda1 will this get published as a v5 alpha?

**Comment by jeff-phillips-18** [comment]
@dagda1 This should be published in the next v5 pre-release
