### ISSUE TITLE
Topology V5 upgrade requires casting of elements to specific element subclasses.

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/react-topology#75]
**Describe the problem**
Updates to types in v5 cause products to need to cast elements to specific element types

**How do you reproduce the problem?**
Update to the v5 release in a product that uses hooks for drag and drop and others.

**Expected behavior**
Upgrade should be smooth, shouldn't have to cast element parameters to specific element sub-classes

**Is this issue blocking you?**
No

**What is your product and what release date are you targeting?**
OpenShift Console

**Comment by jessiehuff** [comment]
https://github.com/patternfly/react-topology/pull/76
