### ISSUE TITLE
Bending the edges

### ISSUE THREAD

**Issue by djuraev** [patternfly/react-topology#86]
I am working with topology. I need to bend edges between nodes. 
Is there any sample or tutorial for it? I cannot find sample on provided examples.

**Comment by jenny-s51** [comment]
Hi @djuraev , we support bend points and they can be created with the Dagre layout.

You can see the topology demo app here https://topology-demo-latest.surge.sh/ 

If you click Basic in the sidebar and then "Single Node Demo" tab, you will see a good example of a bent edge between nodes.

You can see the demo code and how the bendpoints are implemented here: https://github.com/patternfly/react-topology/blob/d4d05b9d75b1f4475b7708d25da1037b8f51ce59/packages/demo-app-ts/src/demos/Basics.tsx#L76-L78

**Comment by jeff-phillips-18** [comment]
Closing this issue as @jenny-s51 has answered with some example source. Please re-open if you feel you need more information or you can ask on slack (https://patternfly.slack.com/archives/CK7URGJ2W)
