### ISSUE TITLE
Using vite as bundler breaks the application

### ISSUE THREAD

**Issue by lordrip** [patternfly/react-topology#96]
**Describe the problem**
The `SVGArrowMarker` component tries to use the `global` object. When using `vite` as a bundler, this object seems to not be available, therefore making the application crash.

**How do you reproduce the problem?**
1. Checkout [this branch](https://github.com/lordrip/kaoto-next/tree/react-topology-test)
2. Install dependencies with `yarn install`
3. Run `yarn workspace @kaoto-next/ui run start`
4. Open the following URL `http://localhost:5173/#/`
5. Notice the stack-trace in the console.

**Expected behavior**
When using `vite` it should work.

**Is this issue blocking you?**
Following [this answer on SO](https://stackoverflow.com/a/73208485/5647849) helped.

In a nutshell, adding:
```html
    <script type="module">
      window.global ||= window;
    </script>
```
into the index.html helped, but the problem will continue if vite is used as a library bundler since the consumer would need to add the workaround as well.

**Screenshots**
##### Stacktrace
![image](https://github.com/patternfly/react-topology/assets/16512618/b0f9cd02-d6ee-4fee-85eb-624cfd1bb3a6)

##### Component source code
![image](https://github.com/patternfly/react-topology/assets/16512618/234ca577-559a-40f0-ad6c-54eee171e245)

**What is your environment?**
- OS: Fedora 38 CSB
- Browser: Firefox developer edition
- Version: 117.0b9 (64-bit)

**What is your product and what release date are you targeting?**
* Project: [Kaoto](https://github.com/KaotoIO/kaoto-next)
* release date: 2024/Q1 (A workaround is available in the meantime)

**Any other information?**

**Comment by nicolethoen** [comment]
It's worth attempting to evaluate and possibly remove references to 'global' and 'window' in general since that makes it much more difficult to bundle topology.
